events { 
    worker_connections 1024; 
}

http {
    upstream springboot_backend {
        server spring1:8080;
        server spring2:8080;
    }

    server {
        listen 80;
        server_name app.fiipractic.lan;

        location /spring1/ {
            proxy_pass http://spring1:8080/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /spring2/ {
            proxy_pass http://spring2:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://springboot_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
